baseURL: /
disablePathToLower: true
languageCode: en-us
MetaDataFormat: yaml
pagination:
  pagerSize: 12
  path: page
enableInlineShortcodes: true
DisqusShortname: sebastienlevert
title: "Seb's on #Microsoft365Dev"
copyright: 'Copyright © Sébastien Levert'
theme: ['hugo-notice', 'hugo-theme-chunky-poster']
summaryLength: 30
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 0
    - identifier: series
      name: Series
      url: /series/
      weight: 0
taxonomies:
  category: categories
  tag: tags
  series: series

permalinks:
  post: /:year/:month/:day/:slug/
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  authors:
    - sebastien-levert
  description: >-
    Sébastien Levert's thoughts, stories and ideas around the Microsoft 365 Development platform!
  dateFormat: 'January 2, 2006'
  showLanguageSwitcher: false
  share: true
  customCSS:
    - styles.css
  prismJS:
    enable: true
    theme: tomorrow
  clarity:
    enable: true
    trackingCode: 6bhi7msiik
  appInsights:
    enable: true
    instrumentationKey: 076077d4-65ce-4d55-af42-8d9d9b331352
  social:
    rss: true
    mastodon: 'https://fosstodon.org/@sebastienlevert'
    twitter: 'https://twitter.com/sebastienlevert'
    bluesky: 'https://bsky.app/profile/sebastienlevert.com'
    linkedin: 'https://www.linkedin.com/in/sebastienlevert/'
    github: 'https://github.com/sebastienlevert'
