baseURL = "https://www.sebastienlevert.com"
disablePathToLower = true
languageCode = "en-us"
MetaDataFormat = "yaml"
paginate = 2
enableInlineShortcodes = true
DisqusShortname = "sebastienlevert"
title = "Seb's on #Microsoft365Dev"
copyright = "Copyright © 2015–2021, Sébatien Levert"
googleAnalytics = "UA-64259172-1"
theme = "hugo-theme-chunky-poster"
summaryLength = 40

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "series"
    name = "Series"
    url = "/series/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]  
  author = "Sébastien Levert"
  description = "Sébastien Levert's thoughts, stories and ideas around the Microsoft 365 Development platform!"
  dateFormat = "January 2, 2006"
  showLanguageSwitcher = false
  share = true
  [params.prismJS]
    enable = true
    theme = "okaidia"

  [params.social]
    rss = true
    twitter = "https://twitter.com/sebastienlevert"
    linkedin = "https://www.linkedin.com/in/sebastienlevert/"
    github = "https://github.com/sebastienlevert"